### ISSUE TITLE
Running latest version creates a Node 12 warning in Github actions

### ISSUE THREAD

**Issue by ni-mkrieg** [eregon/publish-release#10]
I believe you need to change this in action.yml:
```runs:
  using: "node16"
```

>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16...

**Comment by eregon** [comment]
https://github.com/eregon/publish-release/releases/tag/v1.0.5

**Comment by ni-mkrieg** [comment]
wow record time fix, thanks so much @eregon 😄
