### ISSUE TITLE
FR: assign tag to release

### ISSUE THREAD

**Issue by edalzell** [eregon/publish-release#6]
Hi there, great action, thanks!

In my flow I have a draft release that is NOT attached to a tag, and your action is triggered when a tag is pushed. I would love it if we could attach the pushed tag to the `updateRelease` call.

Are you open to a PR that does this?

Here's what the code would look like (this is from another action but using the same `updateRelease` GitHub call:
<img width="420" alt="CleanShot 2022-06-12 at 10 49 27@2x" src="https://user-images.githubusercontent.com/6069653/173246549-71976dcc-9ec3-4521-b749-ad7ac307d1e8.png">

**Comment by eregon** [comment]
Hello, feel free to make/open a PR.
If it's simple enough I might merge it, and otherwise then you have a working fork with the functionality you need.

**Comment by eregon** [comment]
I'm a bit confused by your use case though, if the tag already exists, then `create-release` should just use it anyway, no?

**Comment by edalzell** [comment]
Took a different approach, not needed anymore.
